### ISSUE TITLE
Awsume complains about not being sourced, even when configure has been run

### ISSUE THREAD

**Issue by joebywan** [trek10inc/awsume#181] opened 2022-03-29 23:49 UTC
OS is linux mint 20.3 cinnamon.

I've run awsume-configure and it's added the following to my ~/.profile:

`#AWSume alias to source the AWSume script
alias awsume="source awsume"

#Auto-Complete function for AWSume
_awsume() {
    local cur prev opts
    COMPREPLY=()
    cur="${COMP_WORDS[COMP_CWORD]}"
    prev="${COMP_WORDS[COMP_CWORD-1]}"
    opts=$(awsume-autocomplete)
    COMPREPLY=( $(compgen -W "${opts}" -- ${cur}) )
    return 0
}
complete -F _awsume awsume
`

I've tried creating and adding it to ~/.bashrc also, no luck there.

Any suggestions?  Anymore info I can provide?

**Comment by rozhok** [comment] 2022-10-05 10:29
Same for me, Linux Mint 20.3.
Even worse, awsume crashes terminal session.

**Comment by eva-mueller-coremedia** [comment] 2022-10-05 11:42
Did you try to update the alias by using the absolute path `alias awsume="source <PATH/TO/AWSUME>/awsume"` 
Check in a new tab (or `source ~/.bashrc` resp. `source ~/.bash_profile`)

**Comment by LucasZielke** [comment] 2022-10-05 17:10
I notice this issue, including where awsume crashes the terminal session, only when I have more than one install of awsume, such as where its installed with pipx, and in a seperate venv.

**Comment by JalfResi** [comment] 2023-06-01 07:53
I had the same issue, however I realised that I had installed Awsume outside of a venv. Once I uninstalled it, and installed it again inside my venv, everything worked perfectly.

**Comment by mtskillman** [comment] 2023-09-12 20:23
issue resolved by https://github.com/trek10inc/awsume/issues/183 -> root cause pertains to dash being default shell on Debian systems.

**Closed by mtskillman** 2023-09-12 20:23 UTC
Labels: bug, question
